blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask a question?
    url: https://github.com/voightco/.github/blob/main/support.md
    about: Ask questions and discuss with other community members
